name: CD

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: Live
      url: ${{ vars.WEBSITE_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}'
          credentials_file_path: '${{ github.workspace }}/google-application-credentials.json'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Deploy
        run: npm run firebase:deploy -- --only hosting,firestore:rules,firestore:indexes
